// 获取项目列表
export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
export const RESOLVE_PROJECT_GET_LIST = 'RESOLVE_PROJECT_GET_LIST';

// 嗅探数据库列表
export const GET_DATABASE_LIST = 'GET_DATABASE_LIST';
export const RESOLVE_DATABASE_LIST = 'RESOLVE_DATABASE_LIST';

// 创建项目
export const POST_CREATE_PROJECT = 'POST_CREATE_PROJECT';
export const RESOLVE_CREATE_PROJECT = 'RESOLVE_CREATE_PROJECT';

// 修改项目
export const PUT_EDIT_PROJECT = 'PUT_EDIT_PROJECT';
export const RESOLVE_EDIT_PROJECT = 'RESOLVE_EDIT_PROJECT';

// 删除项目
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const RESOLVE_DELETE_PROJECT = 'RESOLVE_DELETE_PROJECT';

// 查询项目
export const SEARCH_PROJECTS = 'SEARCH_PROJECTS';
export const RESOLVE_SEARCH_PROJECTS = 'RESOLVE_SEARCH_PROJECTS';

// 检测数据源连通
export const CHECK_RESOURCE_CONNECT = 'CHECK_RESOURCE_PROJECTS';
export const RESOLVE_RESOURCE_CONNECT = 'RESOLVE_RESOURCE_PROJECTS';

// 校验项目名
export const CHECK_PROJECT_NAME = 'CHECK_PROJECT_NAME';
export const RESOLVE_PROJECT_NAME = 'RESOLVE_PROJECT_NAME';
