// 项目信息
export const GET_PROJECT = 'GET_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const RESOLVE_GET_PROJECT = 'RESOLVE_GET_PROJECT';
// 页面列表
export const GET_HOME_PAGEINFO = 'GET_HOME_PAGEINFO';
export const RESOLVE_GET_HOME_PAGEINFO = 'RESOLVE_GET_HOME_PAGEINFO';
// 当前选择页面
export const SET_SELECTED_PAGEID = 'SET_SELECTED_PAGEID';
// 当前选择组件
export const SET_SELECTED_COMIDS = 'SET_SELECTED_COMIDS';
// 页面字段
export const GET_PAGEINFO_FIELDS = 'GET_PAGEINFO_FIELDS';
export const RESOLVE_GET_PAGEINFO_FIELDS = 'RESOLVE_GET_PAGEINFO_FIELDS';
// 页面配置
export const RESOLVE_GET_PAGEINFO_CONFIG = 'RESOLVE_GET_PAGEINFO_CONFIG';
// 页面数据
export const GET_PAGEINFO_DATA = 'GET_PAGEINFO_DATA';
export const RESOLVE_GET_PAGEINFO_DATA = 'RESOLVE_GET_PAGEINFO_DATA';
// 页面数据详情
export const GET_PAGEINFO_DATA_DETAIL = 'GET_PAGEINFO_DATA_DETAIL';
export const RESOLVE_GET_PAGEINFO_DATA_DETAIL = 'RESOLVE_GET_PAGEINFO_DATA_DETAIL';
// 页面配置
export const SET_PAGE_CONFIG = 'SET_PAGE_CONFIG';